import { Scenario } from '../types';

export const SCENARIOS: Scenario[] = [
  // ─── GRACE: Empathy Specialist ───────────────────────────────────────────────
  {
    id: 'elderly-chan',
    name: 'Mrs. Chan — Flooded Flat',
    description: 'Elderly Cantonese-speaking customer, flat flooded, scared and confused',
    expectedAgent: 'grace',
    customerName: 'Mrs. Chan',
    language: 'zh',
    messages: [
      { delayMs: 0, content: '你好，我係Chan太太。我屋企入晒水，我唔知點算...' },
      { delayMs: 4000, content: '我78歲，一個人住，好驚...' },
      { delayMs: 8000, content: '客廳地板已經有水，我搬唔到啲嘢' },
    ],
  },
  {
    id: 'window-distressed',
    name: 'Sarah Lam — Window Exploded',
    description: 'Typhoon smashed window, young mother distressed, child present',
    expectedAgent: 'grace',
    customerName: 'Sarah Lam',
    language: 'en',
    messages: [
      { delayMs: 0, content: "My window just exploded during the storm. I'm terrified. Glass everywhere." },
      { delayMs: 4000, content: "My 3 year old is here. Wind and rain coming in. I don't know what to do." },
      { delayMs: 7000, content: 'I need help NOW. This is an emergency.' },
    ],
  },
  {
    id: 'elderly-cantonese-alone',
    name: '陳婆婆 — Flooded & Injured',
    description: 'Elderly Cantonese speaker, flooded, fell and hurt herself, no family nearby',
    expectedAgent: 'grace',
    customerName: '陳婆婆',
    language: 'zh',
    messages: [
      { delayMs: 0, content: '喂，你好。我係老人家，我屋企入晒水，我唔知點算，好驚...' },
      { delayMs: 5000, content: '我跌咗一跤，腳有啲痛，但係我唔想打999，唔想麻煩人' },
      { delayMs: 9000, content: '我一個人住，個仔喺英國，打唔到佢電話' },
    ],
  },
  {
    id: 'mother-baby-no-power',
    name: 'Mei Ling Yu — No Power, Newborn',
    description: 'Mother with 3-month-old baby, power out, flooding starting, very distressed',
    expectedAgent: 'grace',
    customerName: 'Mei Ling Yu',
    language: 'en',
    messages: [
      { delayMs: 0, content: "I have a 3 month old baby and the power has been out for 6 hours. The flat is starting to flood." },
      { delayMs: 4000, content: "I'm really scared. Baby milk needs to be refrigerated and I'm running out of options." },
      { delayMs: 7000, content: "I don't even know if my policy covers temporary accommodation. Can someone help me?" },
    ],
  },
  {
    id: 'post-evacuation-zh',
    name: '林先生 — 撤離後返屋',
    description: 'Cantonese man returned home after evacuation to find severe damage, emotionally shaken',
    expectedAgent: 'grace',
    customerName: '林先生',
    language: 'zh',
    messages: [
      { delayMs: 0, content: '你好，我尋日因為風暴被迫撤離，今日先返到屋企' },
      { delayMs: 4000, content: '屋企一片狼藉，好多嘢都損毀晒，我個心好難受' },
      { delayMs: 8000, content: '我唔知從何入手，可唔可以幫我？我想知我有咩保障' },
    ],
  },
  {
    id: 'elderly-man-confused',
    name: '張伯 — 天花板塌落',
    description: 'Elderly man, ceiling partially collapsed, scared and needs someone to talk to',
    expectedAgent: 'grace',
    customerName: '張伯',
    language: 'zh',
    messages: [
      { delayMs: 0, content: '你好，我係張伯，我今年80歲，個天花板有一部分塌咗落嚟' },
      { delayMs: 5000, content: '我唔受傷，但係好驚，成間屋好亂' },
      { delayMs: 9000, content: '我唔識用電腦，我老伴叫我打呢個號碼，佢話你哋可以幫我' },
    ],
  },
  {
    id: 'nurse-exhausted',
    name: 'Carmen Yuen — Came Home to Damage',
    description: 'Nurse just off a 12-hour shift found flat damaged, exhausted and overwhelmed',
    expectedAgent: 'grace',
    customerName: 'Carmen Yuen',
    language: 'en',
    messages: [
      { delayMs: 0, content: "I just finished a 12-hour hospital shift and came home to a flooded bedroom. I'm so tired I can't think." },
      { delayMs: 5000, content: "The water came in through the window frame. My bed is soaked, I have nowhere to sleep." },
      { delayMs: 8000, content: "I don't even know where my policy documents are. I'm sorry, I'm just overwhelmed." },
    ],
  },

  // ─── SWIFT: Fast-Track Claims ─────────────────────────────────────────────────
  {
    id: 'urgent-david',
    name: 'David Lee — Car Crushed',
    description: 'Urgent: tree fell on car, needs fast claim action',
    expectedAgent: 'swift',
    customerName: 'David Lee',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'Tree fell on my car during the typhoon. Total write-off I think. Need to start a claim NOW.' },
      { delayMs: 4000, content: 'Policy number is HK-MOT-2024-88821. Car is a 2023 Toyota Camry.' },
      { delayMs: 7000, content: 'What do I do next? Can someone come today?' },
    ],
  },
  {
    id: 'roof-tiles-car',
    name: 'Kevin Ho — Roof Tiles on Car',
    description: 'Car park roof tiles fell on vehicle, wants rapid action items',
    expectedAgent: 'swift',
    customerName: 'Kevin Ho',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'Roof tiles fell on my car in the car park. Boot is completely crushed. Policy HK-MOT-2024-76543.' },
      { delayMs: 4000, content: 'I need a recovery truck today and a claim reference number now.' },
      { delayMs: 7000, content: 'When will an assessor see the vehicle? I need a rental car in the meantime.' },
    ],
  },
  {
    id: 'flooded-restaurant',
    name: 'Tommy Leung — Restaurant Flooded',
    description: 'Restaurant owner, ground floor flooded, needs emergency assessor same day',
    expectedAgent: 'swift',
    customerName: 'Tommy Leung',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'My restaurant on Des Voeux Road flooded badly. Ground floor under 30cm of water.' },
      { delayMs: 4000, content: 'Commercial property policy HK-COM-2023-19823. I need an emergency assessor today.' },
      { delayMs: 7000, content: 'I am losing HKD 80,000 a day while closed. What can you do right now?' },
    ],
  },
  {
    id: 'motorcycle-urgent',
    name: 'Peter Tsui — Motorcycle Debris',
    description: 'Motorcycle destroyed by falling signboard debris, fast claim needed',
    expectedAgent: 'swift',
    customerName: 'Peter Tsui',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'A signboard fell on my motorcycle. It is completely destroyed. Ref: HK-MOT-2024-55210.' },
      { delayMs: 4000, content: 'I need to get to work tomorrow. Can I get a claim approved and a rental organised today?' },
      { delayMs: 6000, content: 'Police report number: HKP-2024-08721. Already filed. What are the next steps?' },
    ],
  },
  {
    id: 'two-cars-submerged',
    name: 'Jack Ma — Two Cars Submerged',
    description: 'Homeowner with two cars submerged in flooded car park, high urgency',
    expectedAgent: 'swift',
    customerName: 'Jack Ma',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'Both of my cars are completely submerged in the underground car park. HK-MOT-2024-88210 and HK-MOT-2024-88211.' },
      { delayMs: 4000, content: 'Water is still 1.5 metres deep. Can the insurer arrange pumping and recovery?' },
      { delayMs: 7000, content: 'I need to know what the total loss procedure is. Are both claims processed separately?' },
    ],
  },
  {
    id: 'office-water-damage',
    name: 'Gloria Chan — Office Water Damage',
    description: 'Office manager, ceiling leak destroyed server room equipment, urgent same-day assessor',
    expectedAgent: 'swift',
    customerName: 'Gloria Chan',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'Our office server room ceiling gave way. IT equipment is completely soaked.' },
      { delayMs: 4000, content: 'Policy HK-COM-2024-30021. We cannot operate without this equipment.' },
      { delayMs: 7000, content: 'I need an assessor here this afternoon and emergency IT replacement approval.' },
    ],
  },

  // ─── KARA: Knowledge & FAQ ───────────────────────────────────────────────────
  {
    id: 'policy-question',
    name: 'James Wong — Excess Question',
    description: 'Customer wants to understand their excess before claiming',
    expectedAgent: 'kara',
    customerName: 'James Wong',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'Hi, I have some window damage from the typhoon. Before I claim, what is my excess?' },
      { delayMs: 4000, content: 'Also — does my policy cover water that came in through the broken window?' },
      { delayMs: 7000, content: 'And how long will the claim take?' },
    ],
  },
  {
    id: 'contents-damage',
    name: 'Fiona Ng — TV & Laptop Destroyed',
    description: 'Water ingress destroyed electronics, customer wants to know reimbursement and depreciation',
    expectedAgent: 'kara',
    customerName: 'Fiona Ng',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'My TV and laptop were destroyed when water came through the ceiling. How much will I get back?' },
      { delayMs: 4000, content: 'I paid HKD 18,000 for the TV and HKD 12,000 for the laptop. Policy HK-HOME-2023-44512.' },
      { delayMs: 8000, content: 'Does depreciation apply? TV is 18 months old, laptop is 3 years old.' },
    ],
  },
  {
    id: 'rental-property',
    name: 'Rachel Pang — Rental Property Coverage',
    description: 'Landlord wants to know if typhoon damage to rental flat is covered under home policy',
    expectedAgent: 'kara',
    customerName: 'Rachel Pang',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'I own a flat that I rent out. The tenant says the kitchen ceiling collapsed in the typhoon.' },
      { delayMs: 4000, content: 'My policy is HK-HOME-2022-38811. Does landlord damage like this count under home insurance?' },
      { delayMs: 8000, content: 'Also — can I claim for loss of rental income while the flat is being repaired?' },
    ],
  },
  {
    id: 'home-office-equipment',
    name: 'Grace Au — Home Office Kit',
    description: 'Home worker asks if WFH equipment (monitors, standing desk) is covered under home policy',
    expectedAgent: 'kara',
    customerName: 'Grace Au',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'My home office setup was damaged — two monitors, a standing desk and a webcam. All ruined.' },
      { delayMs: 4000, content: 'I work from home full time. Is business equipment covered under a standard home policy?' },
      { delayMs: 7000, content: 'The kit cost around HKD 25,000. I have receipts for all of it.' },
    ],
  },
  {
    id: 'neighbours-tree',
    name: "Irene Ho — Neighbour's Tree",
    description: "Neighbour's tree fell into customer's garden. Who pays? Third-party liability question",
    expectedAgent: 'kara',
    customerName: 'Irene Ho',
    language: 'en',
    messages: [
      { delayMs: 0, content: "My neighbour's large tree fell into my garden during the storm and damaged my fence and car." },
      { delayMs: 4000, content: 'The tree was clearly dying — I warned them about it twice. Can I claim against them?' },
      { delayMs: 8000, content: 'Or do I claim on my own policy? What happens to my premium if I do?' },
    ],
  },
  {
    id: 'mould-after-flood',
    name: 'Winnie Chu — Mould After Flooding',
    description: 'Customer discovered mould 3 weeks after the typhoon flood, wants to know if covered',
    expectedAgent: 'kara',
    customerName: 'Winnie Chu',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'The typhoon flooded my flat 3 weeks ago. I now have mould growing on three walls.' },
      { delayMs: 4000, content: 'I did not claim at the time because I thought it dried out okay. Can I claim now for the mould remediation?' },
      { delayMs: 8000, content: 'Mould removal quote is HKD 32,000. Is there a time limit on typhoon-related claims?' },
    ],
  },
  {
    id: 'excess-query-zh',
    name: '陳小姐 — 自負額問題',
    description: 'Cantonese customer asking about her excess and claim procedure in Chinese',
    expectedAgent: 'kara',
    customerName: '陳小姐',
    language: 'zh',
    messages: [
      { delayMs: 0, content: '你好，我想問一下我嘅保單，自負額係幾多？我嘅保單號碼係 HK-HOME-2024-67890' },
      { delayMs: 4000, content: '如果我而家索償，會唔會影響我下年嘅保費？' },
      { delayMs: 7000, content: '仲有，我要提交咩文件先可以索償？' },
    ],
  },
  {
    id: 'temporary-accommodation',
    name: 'Andy Lau — Temp Accommodation Cover',
    description: 'Customer evacuated and staying in a hotel, wants to know if costs are covered',
    expectedAgent: 'kara',
    customerName: 'Andy Lau',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'My flat is uninhabitable after the typhoon — ceiling damage, no power. I have been in a hotel for 4 nights.' },
      { delayMs: 4000, content: 'The hotel is costing HKD 1,800 a night. Does my policy cover alternative accommodation?' },
      { delayMs: 8000, content: 'How many nights are covered and what is the daily limit? Policy HK-HOME-2023-55501.' },
    ],
  },

  // ─── PHOENIX: Escalation Handler ────────────────────────────────────────────
  {
    id: 'angry-customer',
    name: 'Richard Tam — Legal Threat',
    description: 'Angry customer, third contact, threatening legal action',
    expectedAgent: 'phoenix',
    customerName: 'Richard Tam',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'This is absolutely ridiculous. I have called THREE TIMES about my roof damage and nothing has happened.' },
      { delayMs: 3000, content: 'I submitted my claim 2 weeks ago. No assessor, no update, nothing. This is unacceptable.' },
      { delayMs: 6000, content: "If I don't hear something concrete today I am calling my lawyer." },
    ],
  },
  {
    id: 'rejected-claim-angry',
    name: 'Brian Yip — Rejected Claim',
    description: 'Customer whose claim was rejected believes it is covered, threatens regulator complaint',
    expectedAgent: 'phoenix',
    customerName: 'Brian Yip',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'My claim was rejected and I completely disagree. The damage is clearly covered under my policy.' },
      { delayMs: 3500, content: 'Your assessor said it was pre-existing damage. That is absolutely false. I have photos from before the typhoon.' },
      { delayMs: 7000, content: "If this isn't reviewed I will be filing a complaint with the Insurance Authority and posting on social media." },
    ],
  },
  {
    id: 'complex-business',
    name: 'Mr. Cheung — Multiple Properties',
    description: 'Business owner with damage across multiple properties, needs senior handler',
    expectedAgent: 'phoenix',
    customerName: 'Mr. Cheung',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'I have three commercial properties all damaged in the typhoon. All under different policies.' },
      { delayMs: 4000, content: 'Two properties have roof damage, one has flooding. I need all three claims expedited.' },
      { delayMs: 7000, content: 'My business is losing money every day. Who is the senior person I can speak with?' },
    ],
  },
  {
    id: 'assessor-dispute',
    name: 'Simon Kwok — Assessor Dispute',
    description: 'Customer disputes assessor valuation, threatening to escalate to ombudsman',
    expectedAgent: 'phoenix',
    customerName: 'Simon Kwok',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'Your assessor valued my roof damage at HKD 45,000. Three independent quotes all came in above HKD 80,000.' },
      { delayMs: 4000, content: 'I believe your assessor has severely undervalued the claim. I have the contractor quotes here.' },
      { delayMs: 7000, content: 'I want a second assessment and a formal review. If not I will take this to the Insurance Complaints Bureau.' },
    ],
  },
  {
    id: 'delayed-payout',
    name: 'Danny Fung — Delayed Payout',
    description: 'Approved claim from 6 weeks ago, still not paid out, customer furious',
    expectedAgent: 'phoenix',
    customerName: 'Danny Fung',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'My claim was approved 6 weeks ago. Reference CH-2024-08821. I still have not received a penny.' },
      { delayMs: 3500, content: 'I have chased five times. Each person tells me something different. This is disgraceful service.' },
      { delayMs: 6000, content: 'I need this resolved TODAY or I am going to the press. I know a journalist at the SCMP.' },
    ],
  },
  {
    id: 'fraud-concern',
    name: 'Ivan Ng — Suspicious Contractor',
    description: 'Customer pressured by contractor to inflate claim, wants guidance',
    expectedAgent: 'phoenix',
    customerName: 'Ivan Ng',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'A contractor came to my flat and is pressuring me to put a higher value on the damage for the claim.' },
      { delayMs: 4000, content: "He says he'll do extra work for free if I report more than what's actually damaged. This doesn't feel right." },
      { delayMs: 7000, content: 'I want to do the right thing. Can you advise me? I am worried I already signed something.' },
    ],
  },
  {
    id: 'angry-zh-legal',
    name: '黃先生 — 極度不滿，要求見主管',
    description: 'Very angry Cantonese customer, claim ignored for 3 weeks, demands senior manager',
    expectedAgent: 'phoenix',
    customerName: '黃先生',
    language: 'zh',
    messages: [
      { delayMs: 0, content: '你哋係做咩嘅？我三個禮拜前已經報咗案，到依家都冇人理我！' },
      { delayMs: 4000, content: '我要求見主管！唔係普通客服！我要即刻有人負責！' },
      { delayMs: 7000, content: '如果今日仲冇回音，我會去投訴保險局，仲會上網公開你哋嘅差勁服務！' },
    ],
  },

  // ─── HUMAN: Escalation to Human Queue ────────────────────────────────────────
  {
    id: 'human-request',
    name: 'Alice Poon — Prefers Human Agent',
    description: 'Customer politely but firmly wants a human agent, not AI',
    expectedAgent: 'human',
    customerName: 'Alice Poon',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'Hi, I have a complicated claim and I would really prefer to speak with a real person.' },
      { delayMs: 4000, content: 'I appreciate AI but this involves my business and I need a human case manager.' },
    ],
  },
  {
    id: 'human-request-zh',
    name: '李太太 — 要求真人',
    description: 'Cantonese customer explicitly requesting a human agent, 真人',
    expectedAgent: 'human',
    customerName: '李太太',
    language: 'zh',
    messages: [
      { delayMs: 0, content: '你好，我知道你係AI，但係我想同真人傾。' },
      { delayMs: 4000, content: '我嘅情況比較複雜，我唔想解釋太多次，可以安排真人幫我嗎？' },
    ],
  },
  {
    id: 'commercial-multi-policy',
    name: 'Michael Cheung — Multi-Policy Commercial',
    description: 'High-value commercial client with 6 properties, needs dedicated case manager',
    expectedAgent: 'human',
    customerName: 'Michael Cheung',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'I am the MD of Cheung Properties Ltd. We have 6 commercial properties affected by the typhoon.' },
      { delayMs: 4000, content: 'Policies HK-COM-2023-10021 through 10026. Total claim value likely exceeds HKD 3 million.' },
      { delayMs: 7000, content: 'I need a dedicated case manager, not a call centre. This is a major account.' },
    ],
  },
  {
    id: 'sensitive-medical',
    name: 'Dr. Lee — Medical Equipment',
    description: 'GP whose clinic was damaged, has sensitive patient records at risk, requires specialist handler',
    expectedAgent: 'human',
    customerName: 'Dr. Lee',
    language: 'en',
    messages: [
      { delayMs: 0, content: 'I run a GP clinic in Wan Chai. We flooded badly and I have patient record servers at risk.' },
      { delayMs: 4000, content: 'This has data protection and medical compliance implications. I need someone who understands this.' },
      { delayMs: 7000, content: 'Policy HK-COM-2024-88010. Please escalate to someone senior with professional indemnity experience.' },
    ],
  },
];
